server:
  port: 8090


spring:
  datasource:
    username: "macros_web_app"
    password: "DUQa3Rc#!0@v" ##Enter your root password
    url: "jdbc:sqlserver://db-cbol-apps-prod.database.windows.net;database=MacrosWebApp;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
    driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect


#spring:
#  datasource:
#    username: "macroswebapp"
#    password: "M4cr0sw3b4pp*2022"
#    url: "jdbc:sqlserver://dwh.cbolivar.com:13144;databaseName=MacrosWebApp"
#    driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
#  jpa:
#    hibernate:
#      ddl-auto: none
#      dialect: org.hibernate.dialect.SQLServerDialect
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SQLServerDialect